api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes and configures the New Relic Java, Python or NodeJS Agent"
  homepage = "https://github.com/dpacheconr/newrelic-paketo-buildpacks"
  id = "newrelic/agent"
  keywords = ["java", "nodejs", "python"]
  version = "1.0.0"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]

[metadata]
  include-files = ["README.md", "bin/build", "bin/detect", "bin/main", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "Enable the New Relic Agent"
    name = "BP_NEW_RELIC_ENABLED"


  # To use different version NR agent, update uri and version variables accordingly
  [[metadata.dependencies]]
    id = "nr-agent-java"
    name = "New Relic Java Agent"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://download.newrelic.com/newrelic/java-agent/newrelic-agent/7.8.0/newrelic-agent-7.8.0.jar"
    version = "7.8.0"

  # To use different version NR agent, update uri and version variables accordingly
  [[metadata.dependencies]]
    id = "newrelic-nodejs"
    name = "New Relic NodeJS Agent"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://registry.npmjs.org/newrelic/-/newrelic-8.14.1.tgz"
    version = "8.14.1"

  # To use different version NR agent, update uri and version variables accordingly
  [[metadata.dependencies]]
    id = "newrelic-python"
    name = "New Relic Python Agent"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://download.newrelic.com/python_agent/release/newrelic-7.12.0.176.tar.gz"
    version = "7.12.0"
    

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
